[workspace]
resolver = "3"
members = [ "numerix", "crates/*" ]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = [ "Xiangong Tang <tangxiangong@gmail.com>" ]

[workspace.dependencies]
nalgebra = "0.33.2"
nalgebra-lapack = "0.25"
nalgebra-sparse = "0.10"
